[build]
base = "ui"
publish = "dist"
command = "npm install && npm run build"

[dev]
command = "npm run dev"
targetPort = 5173
port = 8888
framework = "vite"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
